### ISSUE TITLE
attributes synthax

### ISSUE THREAD

**Issue by mchaptel** [cfourney/OpenHarmony#2]
https://github.com/cfourney/OpenHarmony/blob/6fb3ab774e51170f92e78d995aedc57cf2610cd5/tools/openHarmony_rigging_tools.js#L50

For attribute setting, I also recommend :
```javascript
res.attributes.pivot.setValue(avg);
res.attributes.pivot.setValue(avg, 1);
res.pivot = avg;
```

NB: frame arrays starts at 1 (0 is empty) so that frame numbers and array index match

**Comment by cfourney** [comment]
This should be resolved with the new getter/setter. The res.pivot didn't work in the previous iteration of the dynamic getter/setter. The new version seems to work with this behaviour, and code has been updated to resolve it.
