### ISSUE TITLE
Review new dynamic getter/setter

### ISSUE THREAD

**Issue by cfourney** [cfourney/OpenHarmony#3]
https://github.com/cfourney/OpenHarmony/blob/78cff523fec84b5340760b59411e3e2fff786b54/openHarmony_node.js#L78-L148

What are your thoughts on this? the preview version of the dynamic getter/setter simply didnt seem to work, and there was uncaught errors when the node's attributes already existed as members of that class. 

This new method seems to work, but I'm not convinced that keeping attributes and members in the same place. This at least prevents issues.

**Comment by mchaptel** [comment]
Made a few more pointed comments on the issues I've noticed.
