### ISSUE TITLE
Alert box appears when using $.oGroupNode.prototype.importImageSequence()

### ISSUE THREAD

**Issue by rad1an0** [cfourney/OpenHarmony#62]
Must have been put there for debugging purposes I assume.

**Comment by mchaptel** [comment]
do you have more info? What does the box say?

I'll have a look at it

**Comment by rad1an0** [comment]
2nd line of the $.oGroupNode.prototype.importImageSequence function. Line 3642 in openhamony_node.js

**Comment by mchaptel** [comment]
Sorry for the delay, pushed a fix, it should be ok now in latest commit.
